spring.application.name=spring-batch-example

spring.batch.initialize-schema=always

spring.datasource.jdbcUrl=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

spring.business.datasource.jdbcUrl=jdbc:postgresql://localhost:5432/test01
spring.business.datasource.username=testuser01
spring.business.datasource.password=testpass01
spring.business.datasource.driverClassName=org.postgresql.Driver
